#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | maccms10 命令行入口 (ThinkPHP 8)
// +----------------------------------------------------------------------

define('ROOT_PATH',    __DIR__ . '/');
define('APP_PATH',     __DIR__ . '/application/');
define('RUNTIME_PATH', __DIR__ . '/runtime/');
define('ADDON_PATH',   __DIR__ . '/addons/');
define('MAC_COMM', __DIR__ . '/application/common/common/');
define('MAC_HOME_COMM', __DIR__ . '/application/index/common/');
define('MAC_ADMIN_COMM', __DIR__ . '/application/admin/common/');
define('MAC_START_TIME', microtime(true));
define('ENTRANCE', 'install');
define('IN_FILE', 'think');

ini_set('max_execution_time', '0');
ini_set('memory_limit', '-1');

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit('maccms console entry: CLI only');
}

require __DIR__ . '/vendor/autoload.php';

$app = new \think\App(__DIR__ . '/');
$app->setAppPath(__DIR__ . '/application/');

$console = new \think\Console($app);
$console->run();
