<?php

return array(
    // Default AI Provider
    array(
        'name'    => 'default_provider',
        'title'   => 'AI Provider',
        'type'    => 'select',
        'content' => array(
            'claude'   => 'Claude (Anthropic)',
            'openai'   => 'OpenAI (GPT)',
            'gemini'   => 'Google Gemini',
            'deepseek' => 'DeepSeek',
            'qwen'     => 'Alibaba Qwen',
            'glm'      => 'Zhipu GLM',
        ),
        'value'   => 'claude',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => 'Default AI provider for content generation.',
        'ok'      => '',
        'extend'  => 'id="ai-provider-select" lay-filter="ai-provider-select"',
    ),
    // Default Model
    array(
        'name'    => 'default_model',
        'title'   => 'Model Name',
        'type'    => 'string',
        'content' => array(),
        'value'   => 'claude-sonnet-4-6',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => 'Claude: claude-sonnet-4-6 | OpenAI: gpt-4o | Gemini: gemini-2.0-flash | DeepSeek: deepseek-chat | Qwen: qwen-turbo | GLM: glm-4',
        'ok'      => '',
        'extend'  => '',
    ),

    // --- API Keys ---
    array(
        'name'    => 'claude_key',
        'title'   => 'Claude Key',
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => 'Anthropic API key (console.anthropic.com)',
        'ok'      => '',
        'extend'  => 'data-provider="claude"',
    ),
    array(
        'name'    => 'openai_key',
        'title'   => 'OpenAI Key',
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => 'OpenAI API key (platform.openai.com)',
        'ok'      => '',
        'extend'  => 'data-provider="openai"',
    ),
    array(
        'name'    => 'gemini_key',
        'title'   => 'Gemini Key',
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => 'Google AI Studio API key (aistudio.google.com)',
        'ok'      => '',
        'extend'  => 'data-provider="gemini"',
    ),
    array(
        'name'    => 'deepseek_key',
        'title'   => 'DeepSeek Key',
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => 'DeepSeek platform API key (platform.deepseek.com)',
        'ok'      => '',
        'extend'  => 'data-provider="deepseek"',
    ),
    array(
        'name'    => 'qwen_key',
        'title'   => 'Qwen Key',
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => 'Alibaba DashScope API key (dashscope.console.aliyun.com)',
        'ok'      => '',
        'extend'  => 'data-provider="qwen"',
    ),
    array(
        'name'    => 'glm_key',
        'title'   => 'GLM Key',
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => 'Zhipu AI API key (open.bigmodel.cn)',
        'ok'      => '',
        'extend'  => 'data-provider="glm"',
    ),

    // --- Generation Settings ---
    array(
        'name'    => 'max_tokens',
        'title'   => 'Max Tokens',
        'type'    => 'string',
        'content' => array(),
        'value'   => '1500',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => 'Max tokens in AI response. Recommended: 800-2000.',
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'batch_size',
        'title'   => 'Batch Size',
        'type'    => 'string',
        'content' => array(),
        'value'   => '10',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => 'Items per batch job.',
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'request_timeout',
        'title'   => 'Timeout (s)',
        'type'    => 'string',
        'content' => array(),
        'value'   => '30',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => 'HTTP timeout in seconds for AI API calls.',
        'ok'      => '',
        'extend'  => '',
    ),

    // --- Output Language ---
    array(
        'name'    => 'language',
        'title'   => 'Language',
        'type'    => 'select',
        'content' => array(
            'zh-cn' => 'Chinese Simplified (简体中文)',
            'zh-tw' => 'Chinese Traditional (繁體中文)',
            'en-us' => 'English',
            'ko-kr' => 'Korean (한국어)',
            'ja-jp' => 'Japanese (日本語)',
            'de-de' => 'German (Deutsch)',
            'fr-fr' => 'French (Français)',
            'es-es' => 'Spanish (Español)',
            'pt-pt' => 'Portuguese (Português)',
        ),
        'value'   => 'zh-cn',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => 'Language for AI generated content.',
        'ok'      => '',
        'extend'  => '',
    ),

);
